services:
  myadmin:
    image: myadmin:latest
    build:
      context: ..
      tags:
        - myadmin:latest
      # --- ВИДАЛЕНО ЗВІДСИ ---
      # cache_from:
      #   - type=registry,ref=myadmin:cache
      # cache_to:
      #   - type=registry,ref=myadmin:cache,mode=max
      # --- ДОСІ ---
        
    # (Решта файлу залишається без змін)
    pull_policy: always
    restart: always
    env_file:
      - .env.secrets.prod
    volumes:
      - myadmin-db:/code/db
    labels:
      - "traefik.enable=true"
      # ... (і т.д.)

volumes:
  myadmin-db: